version: '3'
services:
  web:
    image: pranay504/python-webapi
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
      failure_action: rollback
    ports:
    - "5000:5000"

  auth:
    image: pranay504/python-authapi
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
      failure_action: rollback
    ports:
    - "5001:5001"